apiVersion: v1
kind: Pod
metadata:
  name: vlmbench
  namespace: llm-servings
  labels:
    app: vlmbench
spec:
  restartPolicy: Never
  containers:
    - name: vlmbench
      image: amirhossein21/vlmbench:latest
      imagePullPolicy: Always
      workingDir: /workspace/vlmbench
      env:
        - name: REPO_URL
          value: https://github.com/sbu-fsl/vlmbench
        - name: REPO_DIR
          value: /workspace/vlmbench
        - name: KC
          value: "http://llama-1b-models.llm-servings.svc.cluster.local"
        - name: PORT
          value: "80"
        - name: REQUEST_TIMEOUT
          value: "0"
        - name: EXPORT_OUTPUT
          value: "/mnt/gpfs/llm-datasets/vlmbench.txt"
        - name: COMMAND
          value: "python main.py bench --clients 1 local_sharegpt --enable-prometheus-metrics --stop-after 200 --export-output ${EXPORT_OUTPUT} --endpoint ${KC}:${PORT}"
        - name: DEFAULT_DATA_DIR
          value: /mnt/gpfs/llm-datasets
        - name: HF_HOME
          value: /mnt/gpfs/llm-datasets
      volumeMounts:
        - name: llm-datasets
          mountPath: /mnt/gpfs/llm-datasets
  volumes:
    - name: llm-datasets
      hostPath:
        path: /mnt/gpfs/llm-datasets
        type: Directory
